export const dataItems = [
  {
    id: '0',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/card-hitman.jpg?alt=media',
    title: 'hitman 3',
    subtitle: 'IO Interactive',
    discount: '25',
    oldValue: '113,99',
    newValue: '85,49',
    description: '',
    publishing: '',
    plataform: '',
    tags: [],
    favorited: false
  },
  {
    id: '1',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/gta-premium-edition.png?alt=media',
    title: 'Grand Theft Auto V: Premium Exclusive',
    subtitle: 'Rockstar games',
    discount: '50',
    oldValue: '69,99',
    newValue: '34,99',
    description: '',
    publishing: '',
    plataform: '',
    tags: [],
    favorited: false
  },
  {
    id: '2',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/assassins-creed-valhala.webp?alt=media',
    title: 'Assassin\'s Creed: Valhala',
    subtitle: 'Ubisoft Montreal | Ubsoft',
    discount: '25',
    oldValue: '199,99',
    newValue: '149,99',
    description: '',
    publishing: '',
    plataform: '',
    tags: [],
    favorited: false
  },
  {
    id: '3',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/snow-runner.webp?alt=media',
    title: 'SnowRunner',
    subtitle: 'Saber Interactive | Focus Homer',
    discount: '40',
    oldValue: '109,90',
    newValue: '65,94',
    description: '',
    publishing: '',
    plataform: '',
    tags: [],
    favorited: false
  },
  {
    id: '4',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/werewolf.jpg?alt=media',
    title: 'Werewolf: The apocalypse - Ealoy',
    subtitle: 'Cyanide Studio | Nacon',
    discount: '30',
    oldValue: '139,99',
    newValue: '97,99',
    description: '',
    publishing: '',
    plataform: '',
    tags: [],
    favorited: false
  }
]