export const dataItems = [
  {
    id: '0',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/card-hitman.jpg?alt=media',
    imagePageGame: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/hitman-page-game.jpg?alt=media',
    title: 'hitman 3',
    subtitle: 'IO Interactive',
    discount: '25',
    oldValue: '113,99',
    newValue: '85,49',
    description: '',
    publishing: '',
    plataform: '',
    tags: ['+sold'],
    favorited: false
  },
  {
    id: '1',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/gta-resolution.jpg?alt=media',
    imagePageGame: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/gta-resolution.jpg?alt=media',
    title: 'Grand Theft Auto V: Premium Exclusive',
    subtitle: 'Rockstar games',
    discount: '50',
    oldValue: '69,99',
    newValue: '34,99',
    description: '',
    publishing: '',
    plataform: '',
    tags: [],
    favorited: false
  },
  {
    id: '2',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/assassins-creed-valhala.webp?alt=media',
    imagePageGame: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/Assassin-page-game.png?alt=media',
    title: 'Assassin\'s Creed: Valhala',
    subtitle: 'Ubisoft Montreal | Ubsoft',
    discount: '25',
    oldValue: '199,99',
    newValue: '149,99',
    description: '',
    publishing: '',
    plataform: '',
    tags: [],
    favorited: false
  },
  {
    id: '3',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/snow-runner.webp?alt=media',
    imagePageGame: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/snowrunner-page-game.jpg?alt=media',
    title: 'SnowRunner',
    subtitle: 'Saber Interactive | Focus Homer',
    discount: '40',
    oldValue: '109,90',
    newValue: '65,94',
    description: '',
    publishing: '',
    plataform: '',
    tags: [],
    favorited: false
  },
  {
    id: '4',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/werewolf.jpg?alt=media',
    imagePageGame: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/werewolf-page-game.jpg?alt=media',
    title: 'Werewolf: The apocalypse - Ealoy',
    subtitle: 'Cyanide Studio | Nacon',
    discount: '30',
    oldValue: '139,99',
    newValue: '97,99',
    description: '',
    publishing: '',
    plataform: '',
    tags: [],
    favorited: false
  },
  {
    id: '5',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/outriders.webp?alt=media',
    imagePageGame: '',
    title: 'OUTIRIDERS',
    subtitle: '',
    discount: '',
    oldValue: '',
    newValue: '279,00',
    description: '',
    publishing: '',
    plataform: '',
    tags: ['+sold', 'releases'],
    favorited: false
  },
  {
    id: '6',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/kindon-hearts-2-8.jpeg?alt=media',
    imagePageGame: '',
    title: 'KINDON HEARTS HD',
    subtitle: '',
    discount: '20',
    oldValue: '209,50',
    newValue: '167,96',
    description: '',
    publishing: '',
    plataform: '',
    tags: ['+sold', 'releases'],
    favorited: false
  },
  {
    id: '7',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/kindon-hearts-2-8.jpeg?alt=media',
    imagePageGame: '',
    title: 'KINDON HEARTS HD 2.8',
    subtitle: '',
    discount: '20',
    oldValue: '249,50',
    newValue: '199,96',
    description: '',
    publishing: '',
    plataform: '',
    tags: ['+sold'],
    favorited: false
  },
  {
    id: '8',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/kindon-hearts.jpg?alt=media',
    imagePageGame: '',
    title: 'KINDON HEARTS III + Re Mind',
    subtitle: '',
    discount: '20',
    oldValue: '249,50',
    newValue: '199,96',
    description: '',
    publishing: '',
    plataform: '',
    tags: ['+sold', 'releases'],
    favorited: false
  },
  {
    id: '9',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/kindon-heards-melody-of-memory.jpg?alt=media',
    imagePageGame: '',
    title: 'KINDON HEARTS Melody of Memory',
    subtitle: '',
    discount: '20',
    oldValue: '249,50',
    newValue: '199,96',
    description: '',
    publishing: '',
    plataform: '',
    tags: ['releases'],
    favorited: false
  },
  {
    id: '10',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/rocket-league.jpg?alt=media',
    imagePageGame: '',
    title: 'Rocket League',
    subtitle: '',
    discount: '',
    oldValue: '',
    newValue: '0',
    description: '',
    publishing: '',
    plataform: '',
    tags: ['releases'],
    favorited: false
  },
  {
    id: '11',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/hood-outllaws-legends.jpg?alt=media',
    imagePageGame: '',
    title: 'Hood: Outlaws & Legends',
    subtitle: '',
    discount: '',
    oldValue: '',
    newValue: '109,90',
    description: '',
    publishing: '',
    plataform: '',
    tags: ['coming'],
    favorited: false
  },
  {
    id: '12',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/ruined-king.jpg?alt=media',
    imagePageGame: '',
    title: 'Ruined King: A League of Legends story',
    subtitle: '',
    discount: '',
    oldValue: '',
    newValue: '109,90',
    description: '',
    publishing: '',
    plataform: '',
    tags: ['coming'],
    favorited: false
  },
  {
    id: '12',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/oddwold-soulsstorm.jpg?alt=media',
    imagePageGame: '',
    title: 'Oddworld Soulstorm',
    subtitle: '',
    discount: '',
    oldValue: '',
    newValue: '94,99',
    description: '',
    publishing: '',
    plataform: '',
    tags: ['coming'],
    favorited: false
  },
  {
    id: '13',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/chivalry-2.jpg?alt=media',
    imagePageGame: '',
    title: 'Chivarly 2',
    subtitle: '',
    discount: '',
    oldValue: '',
    newValue: '75,99',
    description: '',
    publishing: '',
    plataform: '',
    tags: ['coming'],
    favorited: false
  },
  {
    id: '14',
    urlImage: 'https://firebasestorage.googleapis.com/v0/b/clone-epic.appspot.com/o/biomutant.jpg?alt=media',
    imagePageGame: '',
    title: 'BIOMUTANT',
    subtitle: '',
    discount: '',
    oldValue: '',
    newValue: '199,00',
    description: '',
    publishing: '',
    plataform: '',
    tags: ['coming'],
    favorited: false
  }
]