export const dataItems = [
  {
    id: '0',
    urlImage: '',
    title: 'hitman 3',
    subtitle: 'IO Interactive',
    discount: '25',
    oldValue: '113,99',
    newValue: '85,49',
    description: '',
    publishing: '',
    plataform: '',
    tags: [],
    favorited: false
  },
  {
    id: '1',
    urlImage: '',
    title: 'Grand Theft Auto V: Premium Exclusive',
    subtitle: 'Rockstar games',
    discount: '50',
    oldValue: '69,99',
    newValue: '34,99',
    description: '',
    publishing: '',
    plataform: '',
    tags: [],
    favorited: false
  },
  {
    id: '2',
    urlImage: '',
    title: 'Assassin\'s Creed: Valhala',
    subtitle: 'Ubisoft Montreal | Ubsoft',
    discount: '25',
    oldValue: '199,99',
    newValue: '149,99',
    description: '',
    publishing: '',
    plataform: '',
    tags: [],
    favorited: false
  },
  {
    id: '3',
    urlImage: '',
    title: 'SnowRunner',
    subtitle: 'Saber Interactive | Focus Homer',
    discount: '40',
    oldValue: '109,90',
    newValue: '65,94',
    description: '',
    publishing: '',
    plataform: '',
    tags: [],
    favorited: false
  },
  {
    id: '4',
    urlImage: './assets/card-hitman.jpg',
    title: 'Werewolf: The apocalypse - Ealoy',
    subtitle: 'Cyanide Studio | Nacon',
    discount: '30',
    oldValue: '139,99',
    newValue: '97,99',
    description: '',
    publishing: '',
    plataform: '',
    tags: [],
    favorited: false
  }
]